### ISSUE TITLE
Image is not running on internal OSE 3

### ISSUE THREAD

**Issue by mlabuda** [maxandersen/yellowhat#5]
When deploying a docker image build from the docker file, it is running on docker and local OpenShift (the one part of CDK). But when trying to deploy to internal OSE instance, pod for deployment is created and created an application pod, which is restarting all the time because of status error. Pod status is CrashLoopBackOff. We set up file permissions in Dockerfile, at least we think we set it up.

Error from pod log:

> /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra (LoadError)
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in`require'
>     from server.rb:1:in `<main>'

@smarterclayton any idea?

**Comment by aslakknutsen** [comment]
I just pushed the last attempt at the permissions stuff. Setting .gem as well, but seems to have same result locally.
